version: "3"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener_test
    ports:
      - "5432:5432"

  web:
    build: .
    # wait 5s for db to be loaded, run alembic upgrade, start uvicorn in background, wait 5s to server to start, run tests
    command: bash -c "sleep 5 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 10 && pytest"
    volumes:
      - .:/app
    env_file:
      - test.env
    ports:
      - "8000:8000"
    depends_on:
      - db

#  pgadmin:
#    container_name: pgadmin4
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
#      - PGADMIN_DEFAULT_PASSWORD=postgres
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
