"""initial

Revision ID: 6e1647f5f35c
Revises: faef9ecf8cbd
Create Date: 2022-04-10 21:24:29.771696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1647f5f35c'
down_revision = 'faef9ecf8cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
