"""initial

Revision ID: 99d63c0261fa
Revises: 0d2c8a94c44b
Create Date: 2022-04-10 20:50:19.389342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d63c0261fa'
down_revision = '0d2c8a94c44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
