"""initial

Revision ID: faef9ecf8cbd
Revises: 99d63c0261fa
Create Date: 2022-04-10 21:01:09.451966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faef9ecf8cbd'
down_revision = '99d63c0261fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=8), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('user_username', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_hash'), 'urls', ['hash'], unique=True)
    op.create_index(op.f('ix_urls_id'), 'urls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_id'), table_name='urls')
    op.drop_index(op.f('ix_urls_hash'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
